name: Discord Notification

on:
  pull_request:
    types:
      - opened

jobs:
  discord-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord notification
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        message: 'New Pull Request created!'
